name: firecrawl

x-common-env: &common-env
  REDIS_URL: ${REDIS_URL:-redis://redis:6379}
  REDIS_RATE_LIMIT_URL: ${REDIS_RATE_LIMIT_URL:-redis://redis:6379}
  PLAYWRIGHT_MICROSERVICE_URL: ${PLAYWRIGHT_MICROSERVICE_URL:-https://playwright.martin-linde.com/scrape}
  USE_DB_AUTHENTICATION: ${USE_DB_AUTHENTICATION}
  OPENAI_API_KEY: ${OPENAI_API_KEY}
  OPENAI_BASE_URL: ${OPENAI_BASE_URL}
  MODEL_NAME: ${MODEL_NAME}
  MODEL_EMBEDDING_NAME: ${MODEL_EMBEDDING_NAME}
  OLLAMA_BASE_URL: ${OLLAMA_BASE_URL}
  SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}
  BULL_AUTH_KEY: ${BULL_AUTH_KEY}
  TEST_API_KEY: ${TEST_API_KEY}
  POSTHOG_API_KEY: ${POSTHOG_API_KEY}
  POSTHOG_HOST: ${POSTHOG_HOST}
  SUPABASE_ANON_TOKEN: ${SUPABASE_ANON_TOKEN}
  SUPABASE_URL: ${SUPABASE_URL}
  SUPABASE_SERVICE_TOKEN: ${SUPABASE_SERVICE_TOKEN}
  SELF_HOSTED_WEBHOOK_URL: ${SELF_HOSTED_WEBHOOK_URL}
  SERPER_API_KEY: ${SERPER_API_KEY}
  SEARCHAPI_API_KEY: ${SEARCHAPI_API_KEY}
  LOGGING_LEVEL: ${LOGGING_LEVEL}
  PROXY_SERVER: ${PROXY_SERVER}
  PROXY_USERNAME: ${PROXY_USERNAME}
  PROXY_PASSWORD: ${PROXY_PASSWORD}
  SEARXNG_ENDPOINT: ${SEARXNG_ENDPOINT}
  SEARXNG_ENGINES: ${SEARXNG_ENGINES}
  SEARXNG_CATEGORIES: ${SEARXNG_CATEGORIES}

  NUQ_DATABASE_URL: postgresql://firecrawl:nfkrSgsrR6SG38D@dokploy-postgres.1.jl29mw14l7r8ym604rgx43cpz:5432/firecrawl
  DATABASE_URL: postgresql://firecrawl:nfkrSgsrR6SG38D@dokploy-postgres.1.jl29mw14l7r8ym604rgx43cpz:5432/firecrawl
  NUQ_RABBITMQ_URL: amqp://guest:guest@localhost:5672
  PGHOST: pg-firecrawl

services:
  api:
    image: ghcr.io/firecrawl/firecrawl:latest
    environment:
      <<: *common-env
      HOST: "0.0.0.0"
      PORT: ${INTERNAL_PORT:-3002}
      FLY_PROCESS_GROUP: app
      ENV: local
    depends_on:
      - redis
    expose:
      - "${INTERNAL_PORT:-3002}"
    labels:
      - traefik.enable=true
      - traefik.http.routers.firecrawl-api.rule=Host(`firecrawl.martin-linde.com`)
      - traefik.http.routers.firecrawl-api.entrypoints=websecure
      - traefik.http.routers.firecrawl-api.tls.certresolver=letsencrypt
      - traefik.http.services.firecrawl-api.loadbalancer.server.port=3002

  worker:
    image: ghcr.io/firecrawl/firecrawl:latest
    environment:
      <<: *common-env
      FLY_PROCESS_GROUP: worker
      ENV: local
    depends_on:
      - redis
      - api

  redis:
    image: redis:alpine
    command: redis-server --bind 0.0.0.0
